= Vedleggshåndtering

Vedlegg kan benyttes i en EHF Faktura eller -Kreditnota for å gi tilleggsopplysninger som underbygger det kravet som er fremsatt i selve fakturaen. Aktuelle tilleggsopplysninger kan for eksempel være timelister, kvitteringer, flybilletter osv. Vedlegg skal i utgangspunktet ikke benyttes for å overføre en «pdf-versjon» av fakturaen.  Er det gode grunner til å overføre en «PDF-versjon»  SKAL feltet for dokumenttype ha verdien «Commercial invoice» for faktura og «Credit note» for kreditnota.
Feltet for å sende vedlegg i formatet er valgfritt og kan gjentas mange ganger. Det er for eksempel grafikk, image eller andre tilleggsopplysninger som kan være et vedlegg til en faktura eller kreditnota. Vedlegget kan da sendes som et binært objekt knyttet til meldingen, eller at det overføres en referanse til stedet hvor vedlegget er lagret, for eksempel en URL.

Det er anbefalt å sende tilleggsinformasjon innebygd i dokumentet og ikke som eksternt vedlegg, da mange virksomheter ikke kan gå ut på eksterne lenker for å se tilleggsinformasjonen.
Dersom eksterne vedlegg benyttes, er kjøper forpliktet til å laste ned innholdet bak lenken, og lagre dette selv med kontrollspor til fakturaen/kreditnotaen. En slik løsning krever, i henhold til Skattedirektoratet, en særskilt avtale mellom partene. Bruk av eksterne vedlegg anbefales derfor ikke.

Andre anbefalinger:

Koding:::
Base64
Dokumentformat:::
MIME typer anbefales:
* Pdf – applikasjon / pdf
* TXT – tekst / txt
* GIF – image / gif
* TIFF – image / tiff
* JPEG, JPG – image / jpeg
* PNG – image / png
Størrelse:::
5MB
Beskrivelse av vedlegg:::
Det anbefales å gi en god beskrivelse av hva slag vedlegg det gjelder. Kodelisten DocumentTypeCode anbefales brukt og beskrivelsen gjøres i feltet: Invoice/Additional_DocumentReference/DocumentReference/DocumentType. +
Elementet benyttes kun til å gi en beskrivelse av vedleggets innhold eller type dokument/vedlegg.

== Kopi av faktura/kreditnota som vedlegg

Vedlegg skal i utgangspunktet ikke benyttes for å overføre en «pdf-versjon» av fakturaen/kreditnotaen.  Det er kun i ett tilfelle hvor det er lovpålagt med kopi av selve fakturaen/kreditnotaen som vedlegg:  I de tilfeller fakturautsteder benytter seg av en fakturaportal, hvor fakturautsteder har fakturert/kreditert i eget økonomi/faktura system. I denne situasjon skal fakturautsteder taste inn fakturainformasjonen som finnes på den systemgenererte fakturaen/kreditnotaen, for så å legge ved et bilde av original faktura/kreditnota.  I dette tilfellet SKAL feltet for dokumenttype ha verdien «Commercial  invoice» for faktura og «Credit note» for kreditnota.
