= Value Added Tax (Norwegian MVA)

VAT categories used in Norway as of july 1, 2013 are specified in the table below.  Use of other VAT categories than those specified below leads to rejection of the XML instance document during validation.

[cols="1,5,2",options="header"]
!===
| VAT categori
| Description
| Rate as of july 1, 2013

s| S | Outgoing VAT, ordinary rate | 25%
s| H | Outgoing VAT, reduced rate – food & beverage | 15%
s| R | Outgoing VAT, reduced rate  – raw fish | 11,11%
s| AA | Outgoing VAT, low rate | 8%
s| E | VAT excempt | 0%
s| Z | VAT excempt (Goods and services not included in the VAT regulations) | None (0%)
s| K | Emission allowances for private or public businesses  – buyer calculates VAT | None (0%)
!===

The VAT category must be specified on line level.  On the header level both the VAT rate and the category must be specified. In addition the basis for calculating the VAT value, the VAT value itself and the total amount for VAT  must be specified on the header level.

Cf. chapter 6.3.3.3 for an XML example regarding VAT.

== Currency other than NOK

In cases when invoices are issued in other currencies than the national currency of the seller, the seller may be required to provide information about the VAT total amount in his national currency.

TaxTotal/TaxAmount is given in the DocumentCurrency, whilst the element TransactionCurrencyTaxAmount is used for the tax amount pr. Category in local currency (TaxCurrency). The conversion between DocumentCurrency and TaxCurrency is found in the composite element TaxExchangeRate.

Example: Invoice total EUR 900 EUR exclusive VAT. Exchange rate EUR/NOK = 8.3804

[source,xml]
----
.....
<cbc:DocumentCurrencyCode listID="ISO4217">EUR</cbc:DocumentCurrencyCode>
<cbc:TaxCurrencyCode listID="ISO4217">NOK</cbc:TaxCurrencyCode>
.....
<cac:TaxExchangeRate>
	<cbc:SourceCurrencyCode listID="ISO4217">EUR</cbc:SourceCurrencyCode>
	<cbc:TargetCurrencyCode listID="ISO4217">NOK</cbc:TargetCurrencyCode>
	<cbc:CalculationRate>8.3804</cbc:CalculationRate>
	<cbc:MathematicOperatorCode>Multiply</cbc:MathematicOperatorCode>
	<cbc:Date>2014-02-20</cbc:Date>
</cac:TaxExchangeRate>
<cac:TaxTotal>
	<cbc:TaxAmount currencyID="EUR">225.00</cbc:TaxAmount>
	<cac:TaxSubtotal>
		<cbc:TaxableAmount currencyID="EUR">900.00</cbc:TaxableAmount>
		<cbc:TaxAmount currencyID="EUR">225.00</cbc:TaxAmount>
		<cbc:TransactionCurrencyTaxAmount currencyID="NOK">1885.59</cbc:TransactionCurrencyTaxAmount>
		<cac:TaxCategory>
			<cbc:ID schemeID="UNCL5305">S</cbc:ID>
			<cbc:Percent>25</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:TaxCategory>
	</cac:TaxSubtotal>
</cac:TaxTotal>
.....
----
