= Profiles and Messages

In line with the underlying methodology for the EHF formats (cf. link:http://www.cenbii.eu/[CEN BII]) the electronic messages included in a specific format will be exchanged between the parties as a part of an electronic collaboration process – a profile.

CEN BII has defined a profile as “A specification of how one or more Business Processes are executed by specifying the business rules governing its business collaborations and the information content (data model) of the electronic business transactions exchanged.”

If possible, the EHF is using profiles prepared by link:{link-cen-bii}[BII] or link:{link-peppol}[PEPPOL]. Examples of relevant profiles are:

[cols="3,5", options="header"]
|===

| Profile
| Document types

| Invoice only (bii04)
| Invoice

| Credit note only (biixx)
| Credit note

| Invoice and credit note (bii05)
| Invoice, Credit note

| Invoice, credit note and reminder (biixy)
| Invoice, Credit note, Reminder

| Order and invoice (bii06)
| Order, Order response, Invoice, Credit note

|===

The messages being exchanged within a profile are customized to comply with the requirements given for that particular business document.

A CustomizationID is used to identify the business rules that apply to the document in question, i.e. the whole set of business rules the document issuer founded the document on.

The example CustomizationID below indicates that the contents of the current message is based on business rules determined by BII (urn:www.cenbii.eu:transaction:biitrns010:ver2.0), extended, customized and clarified by PEPPOL (urn:www.peppol.eu:bis:peppol5a:ver2.0) and further extended, customized and clarified in this implementation guide regarding the Norwegian businesses  (urn:www.difi.no:ehf:faktura:ver2.0).

[source]
----
<cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns10:ver2.0:extended:urn:www.peppol.eu:bis:peppol5a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0</cbc:CustomizationID>
----
