[preface]
= Freface

== Background and Objective

The government white paper labeled “St.Meld. nr. 36 (2008-2009) Det gode innkjøp” (The good procurement), states among other things:

[quote]
It’s the Government’s opinion that increased use of electronic solutions is important to improve and increase the efficiency of public procurement. The use of electronic solutions may reduce time spent on public procurement, increase the competition and arrange for purchases to be more transparent and easier to re-examine. By spending less time and money on procurement, resources will be available for both modernizing the public sector and more welfare.
The goal for introducing electronic solutions is to contribute to a better, simpler and more secure procurement.

The previous «Ministry of Government Administration, Reform and Church Affairs» (FAD) considered use of open standards as a vital means to build a well-functioning public administration, with good internal collaboration and a high level of service for both inhabitants and businesses.

[quote]
.Definition of link:http://no.wikipedia.org/wiki/%C3%85pen_standard[open standards]:
An open standard is characterized by its reputation and will be maintained by a non-commercial organization, and the continuing development is based on decision processes open to every interested party. The standard is published and the documentation is available, either free of charge or for a small, insignificant fee. Anyone must be allowed to copy, distribute and use the standard free of charge or for a small, insignificant fee. The intellectual rights related to the standard (e.g. patents) are irrevocably available, without any royalties. There is no reservation regarding re-use of the standard.

*The purpose* of this document is to describe a common format for invoice messages in the Norwegian market, and to facilitate an efficient implementation and increased use of electronic collaboration regarding the invoicing process based on this format


== Target Audience

*The target audience* for this implementation guide is both accounting and IT professionals in organizations aiming at performing the invoicing process completely or partially electronic. That means issuing an invoice, a credit note and a reminder. This document may also benefit system suppliers, ERP suppliers and message brokers.

*	Accounting professionals are advised to read chapters 1 through 5.
*	Chapters 5 through 7 are for both accounting professionals as technical implementers
*	IT professionals may concentrate on chapters 6 through 9.


== Document Structure

This document consists of the following chapters and contents:

*	Chapter 1 gives a short introduction describing the background and objective of this implementation guide.
*	Chapter 2 gives the change history of the document.
*	Chapter 3 describes the EHF formats (Invoice and Credit note) in general.
*	Chapter 4 links to definitions relevant to EHF formats.
*	Chapter 5 links to general principles and conditions for the formats.
*	Chapter 6 describes in detail central information elements.
*	Chapter 7 gives the complete information contents of the invoice and the credit note formats.
*	Chapter 8 deals with validation.
*	Chapter 9 embraces these appendices:
** Appendix 1: Message structure
** Appendix 2: Message matrix
** Appendix 3: Code lists
** Appendix 4: Link to UBL 2.0 schema for invoice and credit note
** Appendix 5: Link to Schematron files used in validation
** Appendix 6: XML example files

Appendices 1, 2 and 6 are separate documents.  Appendices 3, 4 and 5 serve as links to information on the internet.


## Mandatory Use

This version is valid from {date-mandatory}, and is mandatory from the same date.
