= Kvantum og bestillingsmengder

Det er mulig å angi ulike kvantum og enheter som gjelder for en artikkel eller tjeneste i den aktuelle katalogen.  Noen av disse er relatert til bestilling av produktet og andre til logistikk og forpakning.

Følgende kvantum og bestillingsmengder er mulig å angi. For alle kvanta skal det også angis enhet ihht. kodeliste.

Elementnavn i UBL er nevnt i parantes, og er angitt fra CatalogueLine nivå.

Bestillbar enhet (OrderableUnit)::
Enhetskode for aktuelt produkt/pakningsnivå. Påkrevd dersom produktet er bestillbart. Kode ihht. kodeliste.

Innhold i forbruksartikkel /artikler (ContentUnitQuantity)::
Innhold i forbruksartikkel/forbruksartikler i bestillbar enhet, f.eks. ml i Shampo-flaske(r).

Bestillingsintervall (OrderQuantityIncrementNumeric)::
Angir antall enheter som en bestilling kan økes med. Default er 1.

Minimumsbestilling (MinimumOrderQuantity)::
Minimumskvantum som kan bestilles av en bestillbar enhet.

Maksimumsbestilling (MaximumOrderQuantity)::
Maksimumskvantum som kan bestilles.

Pakningskvantum (Item/PackQuantity)::
Angir antall enheter på underliggende nivå, f.eks. D-pak på pall eller F-pak i D-pak.

Antall forbruksartikler (Item/PackSizeNumeric)::
Totalt antall forbruksartikler i aktuelt produkt. F.eks. antall flasker på pall.

.Eksempel 1
====

[cols="5h,2,2,2,2", options="header"]
|===
| Beskrivelse | Element (fra CatalogueLine nivå)| 1 flaske | Kasse med 6 flasker | Pall med 18 kasser
| Linjeidentifikator | ID | 4 | 5 | 6
| Leverandørens artikkelnummer |SellersItemIdentification/ID | 1111 | 111 | 11
| Produktnavn | Item/Name |	Shampoo 250 ml | 6x250 ml Shampoo | Shampoo
| Bestillbar enhet| OrderableUnit | EA | CS | PF
| Pakningsnivå | PackLevelCode | CU | TU | DU
| Pakningskvantum | Item/PackQuantity | | 6 | 18
| Pakningsenhet | Item/PackQuantity/@unitCode | | EA | CS
| Antall forbruksartiker | Item/PackSizeNumeric | 1 | 6 | 108
| Innhold i forbruksartikkel | ContentUnitQuantity | 250 | 1500 | 27000
| Enhetskode for innhold i forbruksartikkel |ContentUnitQuantity/@unitCode | MLT | MLT | MLT
| Minimumsbestilling | MinimumOrderQuantity | 1 | 1 | 1
| Enhetskode for minimumsbestilling | MinimumOrderQuantity/@unitCode | EA | EA | EA
| Identifikator for komponenter | ComponentRelatedItem/ID | |1111 | 111
| Kvantum for komponenter | ComponentRelatedItem/Quantity | | 6 | 18
|===

[source]
.Eksempel på utfylling i EHF katalog av kataloglinje med identifikator = 4 i tabellen over
----
<cac:CatalogueLine>
  <cbc:ID>4</cbc:ID>
  <cbc:OrderableUnit>EA</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="MLT" unitCodeListID="UNECERec20">250</cbc:ContentUnitQuantity>
  <cbc:OrderQuantityIncrementNumeric>1</cbc:OrderQuantityIncrementNumeric>
  <cbc:MinimumOrderQuantity unitCode="EA" unitCodeListID="UNECERec20">1</cbc:MinimumOrderQuantity>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">CU</cbc:PackLevelCode>
  ...
  <cac:Item>
    <cbc:Name languageID="en">Shampoo 250 ml</cbc:Name>
    <cbc:PackSizeNumeric>1</cbc:PackSizeNumeric>
    <cac:SellersItemIdentification>
      <cbc:ID>1111</cbc:ID>
    </cac:SellersItemIdentification>
  ...
  </cac:Item>
  ...
</cac:CatalogueLine>
----
====

.Eksempel 2
====

[cols="5h,2,2,2,2", options="header"]
|===
| Beskrivelse | Element (fra CatalogueLine nivå)| Pakke med 500 ark papir | Kasse med 5 pakker papir | Pall med 18 kasser papir
| Linjeidentifikator | ID | 7 | 8 | 9
| Leverandørens artikkelnummer |SellersItemIdentification/ID | A | AA | AAA
| Produktnavn | Item/Name | 500 copy paper | 5*500 Copy paper | Pallet of paper
| Bestillbar enhet| OrderableUnit | EA | CS | PX
| Pakningsnivå | PackLevelCode | CU | TU | DU
| Pakningskvantum | Item/PackQuantity | | 5 | 18
| Pakningsenhet | Item/PackQuantity/@unitCode | | EA | CS
| Antall forbruksartiker | Item/PackSizeNumeric | 1 | 5 | 90
| Innhold i forbruksartikkel |ContentUnitQuantity | 500 | 2500 | 45000
| Enhetskode for innhold i forbruksartikkel |ContentUnitQuantity/@unitCode | EA | EA | EA
| Minimumsbestilling | MinimumOrderQuantity | 1 | 1 | 1
| Enhetskode for minimumsbestilling | MinimumOrderQuantity/@unitCode | EA | EA | EA
| Identifikator for komponenter | ComponentRelatedItem/ID  | | A | AA
| Kvantum for komponenter | ComponentRelatedItem/Quantity  | | 5 | 18
|===

[source]
.Eksempel på utfylling i EHF katalog av kataloglinje med identifikator = 8 i tabellen over
----
<cac:CatalogueLine>
  cbc:ID>8</cbc:ID>
  <cbc:OrderableUnit>CS</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="EA" unitCodeListID="UNECERec20">2500</cbc:ContentUnitQuantity>
  <cbc:OrderQuantityIncrementNumeric>1</cbc:OrderQuantityIncrementNumeric>
  <cbc:MinimumOrderQuantity unitCode="CS" unitCodeListID="UNECERec20">1</cbc:MinimumOrderQuantity>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">TU</cbc:PackLevelCode>
  <cac:ComponentRelatedItem>
    <cbc:ID>A</cbc:ID>
    <cbc:Quantity unitCode="EA" unitCodeListID="UNECERec20">5</cbc:Quantity>
  </cac:ComponentRelatedItem>
  ...
  <cac:Item>
    <cbc:Description languageID="en">5*500 Copy paper</cbc:Description>
    <cbc:PackQuantity unitCode="CS" unitCodeListID="UNECERec20">5</cbc:PackQuantity>
    <cbc:PackSizeNumeric>5</cbc:PackSizeNumeric>
    <cac:SellersItemIdentification>
      <cbc:ID>AA</cbc:ID>
    </cac:SellersItemIdentification>
    ...
  </cac:Item>
  ...
</cac:CatalogueLine>
----
====

== Mengdevariabel vare

For å angi at en vare er såkalt mengdevariabel (F.eks at man bestiller en vare i stk., men blir fakturert i kilo, der en stk. kan være av variabel vekt), anbefales det å sette enhetskoden for pakningskvantum/innhold til kode 31 (catch weight)  i henhold til UN Recommondation 20.

[source]
.Eksempel på utfylling i EHF katalog.
----
<cac:CatalogueLine>
  <cbc:ID>8</cbc:ID>
  <cbc:OrderableUnit>EA</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="31" unitCodeListID="UNECERec20">10</cbc:ContentUnitQuantity>
  ...
----
