= Merverdiavgift (MVA/VAT)

I EHF Katalog er det definert felt for å angi MVA-sats pr artikkel.  Dette er valgfritt og angis som en kode som definerer aktuell prosentsats. Kjøpere kan stille krav til utfylling av MVA dersom de anser at dette vil gi merverdi for sine bestillere, eller om deres innkjøps-systemer er avhengig av MVA-satsen for å kunne matche ordre med faktura.

Dette må i så fall avtales via kontrakt eller samhandlingsavtale.

Følgende MVA-koder er mulig å angi:

[cols="1,5,2",options="header"]
!===
| MVA kategori
| Beskrivelse
| Sats pr. 1.juli 2013

s| S | Utgående avgift, ordinær sats | 25%
s| H | Utgående avgift, redusert sats – næringsmidler | 15%
s| R | Utgående avgift, redusert sats – råfisk | 11,11%
s| AA | Utgående avgift, redusert sats – lav sats | 10%
s| E | Fritatt for merverdiavgift (avgiftsfritt salg) | 0%
s| Z | Unntatt fra merverdiavgiftsloven (utenfor merverdiavgiftsloven) | Ingen (0%)
s| K | Klimakvoter til næringsdrivende eller offentlig virksomhet – kjøper beregner MVA | Ingen (0%)
!===

[source]
.Eksempel på utfylling
----
<cac:ClassifiedTaxCategory>
  <cbc:ID schemeID="UNECE5305">S</cbc:ID>
  <cac:TaxScheme>
    <cbc:ID>VAT</cbc:ID>
  </cac:TaxScheme>
</cac:ClassifiedTaxCategory>
----
