= Vedleggshåndtering

Vedlegg kan sendes på linjenivå i en katalogmelding. Dette kan for eksempel være bilder av et produkt eller andre tilleggsopplysninger.

Siden vedlegg vil kunne øke filstørrelsen på en katalogmelding vesentlig er det anbefalt å sende dette som en ekstern referanse i form av en URI som peker til en nettside.

[source]
.Eksempel på vedlegg i en EHF katalogmelding.
----
<cac:Item>
  ...
  <cac:ItemSpecificationDocumentReference>
    <cbc:ID>LK8788</cbc:ID>
    <cbc:DocumentDescription>Product image</cbc:DocumentDescription>
    <cac:Attachment>
      <cac:ExternalReference>
        <cbc:URI>http://img.trioving.net/Låskasser/LK8788_PRD_FPM_000.JPG</cbc:URI>
      </cac:ExternalReference>
    </cac:Attachment>
  </cac:ItemSpecificationDocumentReference>
  ...
</cac:Item>
----


== Bruk av kodeliste for vedlegg

For økt kvalitet i bestillingssystemer er det nødvendig med angivelse av hvilken type innhold som er lagt med. For å gjøre dette anbefaler vi å benytte GS1 sin kodeliste link:http://apps.gs1.org/GDD/Pages/clDetails.aspx?semanticURN=urn:gs1:gdd:cl:ReferencedFileTypeCode&release=5[ReferencedFileTypeCode version 5].

[source]
.Eksempel på bruk av ReferencedFileTypeCode på kataloglinje.
----
<cac:Item>
  ...
  <cac:ItemSpecificationDocumentReference>
    <cbc:ID>LK8788</cbc:ID>
    <cbc:DocumentTypeCode listID="urn:gs1:gdd:cl:ReferencedFileTypeCode">PRODUCT_IMAGE</cbc:DocumentTypeCode> <1>
    <cbc:DocumentDescription>Product image</cbc:DocumentDescription>
    <cac:Attachment>
      <cac:ExternalReference>
        <cbc:URI>http://img.trioving.net/Låskasser/LK8788_PRD_FPM_000.JPG</cbc:URI>
      </cac:ExternalReference>
    </cac:Attachment>
  </cac:ItemSpecificationDocumentReference>
  ...
</cac:Item>
----
<1> Angivelse av type vedlegg.


== Formater

Feltet for å sende vedlegg i formatet er valgfritt og kan gjentas mange ganger. Det er for eksempel grafikk, image eller andre tilleggsopplysninger som kan være et vedlegg til en ordremelding. Vedlegget kan da sendes som et binært objekt innebygd i meldingen, eller at det overføres en referanse til stedet hvor vedlegget er lagret, for eksempel en URL. Vedlegg kan kun sendes på hodenivå.

Det er anbefalt å sende tilleggsinformasjon innebygd i dokumentet og ikke som eksternt vedlegg.

Andre anbefalinger:

Koding:::
Base64
Dokumentformat:::
MIME typer anbefales:
* Pdf – applikasjon / pdf
* TXT – tekst / txt
* GIF – image / gif
* TIFF – image / tiff
* JPEG, JPG – image / jpeg
* PNG – image / png
Størrelse:::
5MB
