[preface]
= Bakgrunn

== Bakgrunn og målsetning

I Stortingsmelding nr. 36:2008-2009 Det gode innkjøp står det:

[quote]
Regjeringa meiner auka bruk av elektroniske løysingar er viktig for å forbetre og effektivisere offentleg innkjøp. Bruk av elektroniske løysingar kan redusere tidsbruken ved offentlege innkjøp, auke konkurransen og leggje til rette for innkjøp som er meir gjennomsiktige og lettare kan etterprøvast. Ved å bruke mindre tid og pengar på innkjøp frigjer ein ressursar som kan brukast til både fornying av offentleg sektor og meir velferd.
Målet med å innføre elektroniske løysingar er å medverke til betre, enklare og sikrare innkjøp.

Fornyings- og administrasjonsdepartementet og Kirkedepartementet (FAD) anså bruk av åpne standarder som et grunnleggende element for å skape en velfungerende offentlig sektor, med god intern samhandling og et godt tjenestetilbud til innbyggere og næringsliv.

[quote]
.Definisjon av link:http://no.wikipedia.org/wiki/%C3%85pen_standard[åpen standard]:
En åpen standard kjennetegnes ved at den er anerkjent og vil bli vedlikeholdt av en ikke-kommersiell organisasjon, og det løpende utviklingsarbeidet foregår på basis av beslutningsprosesser som er åpne for alle interesserte parter. Standarden er publisert og dokumentasjonen er tilgjengelig, enten gratis eller til en ubetydelig avgift. Det må være tillatt for alle å kopiere, distribuere og bruke standarden gratis eller for en ubetydelig avgift. Den intellektuelle rettighet knyttet til standarden (eks. patenter) er gjort ugjenkallelig tilgjengelig, uten royalty. Det er ingen forbehold om gjenbruk av standarden.

*Målsetningen* med dette dokumentet er å definere et felles format for pakkseddel meldingen i det norske markedet, og å legge til rette for en effektiv innføring og utbredelse av elektronisk samhandling i leveringsprosessen  basert på dette formatet.


== Målgruppe

*Målgruppen* for dokumentet (heretter omtalt som implementeringsveileder) er både faglig og teknisk personell hos brukere som ønsker å utføre hele eller deler av leveringsprosessen elektronisk. Det vil i praksis si å sende elektronisk pakkseddel. Dokumentet kan også benyttes av systemleverandør, ERP leverandør og meldingsformidlere.

* Kapittel 1 til 5 er rettet mot faglig personell
* Kapittel 5 til 7 er rettet både mot faglig og teknisk personell
* Kapittel 8 til 9 (vedlegg) er rettet mot teknisk personell


== Dokumentstruktur

Dokumentet er inndelt i følgende deler:

. Kapittel 1 gir en kort introduksjon som beskriver bakgrunn og målsetting med implementeringsveileder.
. Kapittel 2 beskriver de endringer som er gjort mellom forskjellige versjoner av implementeringsveilederen.
. Kapittel 3 beskriver EHF formatene generelt.
. Kapittel 4 inneholder definisjoner som er relevant for pakkseddel.
. Kapittel 5 beskriver generelle prinsipper og forutsetninger for pakkseddel.
. Kapittel 6 gir detaljerte beskriver av sentrale informasjonselementer i pakkseddel formatet.
. Kapittel 7 inneholder komplett beskrivelse av informasjonsinnhold i pakkseddel.
. Kapittel 8 omhandler validering, det vil si kontroll av informasjonsinnhold.
. Kapittel 9 inneholder følgende vedlegg:
.. Vedlegg 1: Meldingsstruktur
.. Vedlegg 2: Meldingstabell
.. Vedlegg 3: Kodelister
.. Vedlegg 4: UBL 2.1 schema for pakkseddel
.. Vedlegg 5: Schematron filer som benyttes ved validering
.. Vedlegg 6: XML eksempelfiler
.. Vedlegg 7: Kompatibilitets erklæring

Vedlegg 1,2,6 og 7 er separate dokumenter.  Vedlegg 3, 4 og 5 er kun henvisninger til hvor informasjonen finnes på Internett.

== Ikrafttredelse

Denne revisjonen gjøres tilgjengelig for bruk fra {date-mandatory}. Den vil være obligatorisk fra samme dato.
