= Generelt om katalogmeldingene

De elektroniske meldingene som denne veilederen omfatter er EHF Katalog og EHF Katalogbekreftelse. Kjøper og selger må kunne utveksle begge meldingene elektronisk for å være i overenstemmelse med denne veilederen.

En elektronisk katalog er en strukturert liste med informasjon om varer og tjenester som skal danne grunnlaget for eller understøtte en kjøpshandling. En elektronisk katalog kan dekke ulike funksjoner i forhold til etablering og vedlikehold av kataloginformasjon.

EHF Katalog kan brukes til følgende:

* Opprette en ny katalog
* Erstatte en eksisterende katalog
* Legge til eller slette kataloglinjer
* Endre produktegenskaper og priser på eksisterende kataloglinjer

Ved endringer er det anbefalt å erstatte hele katalogen fremfor å oppdatere enkelte kataloglinjer.

En elektronisk katalog med tilstrekkelig informasjon om leverandørens varer og tjenester vil motvirke feilleveranser som påfører både kjøpere og leverandør kostnader.

Som regel vil en elektronisk katalog agere i samhandling med et katalogverktøy og bli eksponert via et søkeverktøy. En søkemotor kan variere i kompleksitet ved at den kan søke i noen eller mange av feltene i den elektroniske katalogen. Jo flere felter det søkes i jo mer presist vil søkeresultatet bli og sikrere en god kjøpsbeslutning.
