= Konteringsstrengen

Det er ofte et behov for å få angitt hvordan fakturainnholdet skal konteres i mottakers regnskap. Konteringsstrengen er anbefalt sendt på linjenivå forutsatt at leverandøren har mottatt konteringsstrengen fra kjøperen. Angivelse av konteringsstrengen muliggjør automatisk kontering for kjøper.

[source,xml]
.Eksempel
----
<cbc:AccountingCost>Prosjekt kostnadskode 123</cbc:AccountingCost>
----

Siden konteringsstrengen kun er ett enkelt tekstfelt og en kontering i regnskapet gjerne benytter flere «dimensjoner» har en løsning for strukturert innhold i konteringsstrengen vært etterspurt av mange aktører. Nedenfor følger forslag til standardisert innhold i konteringsstreng ved bruk av følgende elementer i strengen:

* Format-ID.  Fast tekst som indikerer vilken kontoplan som benyttes. (NS4102 = norsk standard)
* Feltnavn. Her er det inntil 7 felt som kan benyttes:
** Konto
** Avd (Avdeling)
** Prod (Produkt)
** Prosj (Prosjekt)
** MVAkode
** Dim6
** Dim7
* Verdi
* Verdi skilletegn:  Bruke tegnet  =
* Feltskilletegn: Bruke tegnet ;

Generelt innhold:

<Kontoplan>; Konto=<kontonr>;Avd=<avdeling>;Prod=<produkt>;Prosj=<prosjekt>;MVAkode=<MVA kode i mottakers regnskap>;Dim6=<Benyttes ved behov>;Dim7=<Benyttes ved behov>

Kontoplan må alltid komme først i strengen.  Ingen krav ang. rekkefølge eller innhold i de andre feltene.  Dersom norsk kontoplan benyttes av mottaker, skal NS4102 angis først i konteringsstrengen.  For mottakere som benytter standard kontostreng for landbruk, versjon 1, skal Landbruk_kontostreng_v01 angis.
Er det behov for andre felt i forbindelse med kontering enn konto, avdeling, produkt, prosjekt og MVA kode, kan feltene Dim6 og Dim7 benyttes.  For eksempel er det i landbruksssammenheng behov for et felt for driftsgreinkode.  Dim6 kan benyttes til dette.

[source,xml]
.Eksempel
----
<cbc:AccountingCost>NS4102;Konto=4010;Avd=25;Prod=5421;Prosj=4098;MVAkode=1</cbc:AccountingCost>
----
