= Leverandørens MVA-nummer

Leverandørens MVA nummer angis  i elementet Invoice/cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID og
er opprinnelig et valgfritt felt, men i følge EU COUNCIL DIRECTIVE 2001/115/ må elementet sendes dersom faktura eller kreditnota har en MVA total. Det betyr i praksis at feltet nesten alltid må sendes. For virksomheter registrert i Norge er det organisasjonsnr. etterfulgt av bokstavene MVA (123456789MVA) som skal sendes. Det anbefales bruk av NO som prefiks ved fakturering til utlandet.

[source,xml]
.Eksempel
----
<cac:PartyTaxScheme>
	<cbc:CompanyID schemeID="NO:VAT">123456789MVA</cbc:CompanyID>
	<cac:TaxScheme>
		<cbc:ID>VAT</cbc:ID>
	</cac:TaxScheme>
</cac:PartyTaxScheme>
----

== Leverandører som ikke er registrert for MVA

Dersom leverandør ikke er registrert for MVA, så kan ikke fakturaen inneholde MVA. Det vil si at MVA kategori settes lik "Z", og MVA-beløp settes til 0,-. Elementet 'cac:PartyTaxScheme' skal heller ikke sendes.

[source, xml]
.Eksempel på leverandørinfo:
----
<cac:AccountingSupplierParty>
	<cac:Party>
		<cbc:EndpointID schemeID="NO:ORGNR">999888777</cbc:EndpointID>
		<cac:PartyIdentification>
			<cbc:ID schemeID="GLN">1234567898765</cbc:ID>
		</cac:PartyIdentification>
		<cac:PartyName>
			<cbc:Name>Bedriften A/S</cbc:Name>
		</cac:PartyName>
		<cac:PostalAddress>
			<cbc:StreetName>Brugt. 10</cbc:StreetName>
			<cbc:CityName>Sarpsborg</cbc:CityName>
			<cbc:PostalZone>1710</cbc:PostalZone>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Supplier without VAT</cbc:RegistrationName>
			<cbc:CompanyID schemeID="NO:ORGNR">999888222</cbc:CompanyID>
			<cac:RegistrationAddress>
				<cbc:CityName>Sarpsborg</cbc:CityName>
				<cac:Country>
					<cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
				</cac:Country>
			</cac:RegistrationAddress>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:ID>abc1234</cbc:ID>
		</cac:Contact>
	</cac:Party>
</cac:AccountingSupplierParty>
----

[source, xml]
.Eksempel MVA og totalbeløp
----
<cac:TaxTotal>
		<cbc:TaxAmount currencyID="NOK">0.00</cbc:TaxAmount>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="NOK">100.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="NOK">0.00</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305">Z</cbc:ID>
				<cbc:Percent>0</cbc:Percent>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
	</cac:TaxTotal>

	<cac:LegalMonetaryTotal>
		<cbc:LineExtensionAmount currencyID="NOK">100.00</cbc:LineExtensionAmount>
		<cbc:TaxExclusiveAmount currencyID="NOK">100.00</cbc:TaxExclusiveAmount>
		<cbc:TaxInclusiveAmount currencyID="NOK">100.00</cbc:TaxInclusiveAmount>
		<cbc:PayableAmount currencyID="NOK">100.00</cbc:PayableAmount>
	</cac:LegalMonetaryTotal>
----

[source, xml]
.Eksempler MVA på fakturalinje:
----
<cac:ClassifiedTaxCategory>
	<cbc:ID schemeID="UNCL5305">Z</cbc:ID>
		<cbc:Percent>0</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
</cac:ClassifiedTaxCategory>
----
