= Utbetalingsanmodning

Fra og med versjon 2.0.8 støtter EHF Faktura forsendelse av utbetalingsanmodning for å støtte oppunder prosesser i offentlig sektor. Denne varianten er ikke å anse som en faktura.

WARNING: Utbetalingsanmodning er ikke å regne som en faktura, og bruk utover forhåndsdefinerte prosesser i offentlig sektor er ikke tillatt.


== Angivelse av variant

For identifisering av dokumenttype brukes normale verdier foruten når det gjelder InvoiceTypeCode.

[source]
----
<cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol4a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0</cbc:CustomizationID> <!--1-->
<cbc:ProfileID>urn:www.cenbii.eu:profile:bii04:ver2.0</cbc:ProfileID> <!--2-->
<cbc:ID>108</cbc:ID> <!--3-->
<cbc:IssueDate>2016-01-01</cbc:IssueDate>
<cbc:InvoiceTypeCode listID="UNCL1001">Z02</cbc:InvoiceTypeCode> <!--4-->
----
<1> CustomizationID som for vanlig faktura.
<2> ProfileID som vanlig for faktura i link:#_profil_04_kun_faktura[profil 04].
<3> I stedet for fakturanummer skal en enhetlig referansekode benyttes, eksempelvis saksnummer.
<4> Koden `Z02` angir at dokumentet er en utbetalingsanmodning.


== Aktører

I en utbetalingsanmodning benyttes felter for leverandør for å beskrive betalingsmottaker, mens felter for kjøper benyttes for å beskrive utbetaler.

For utbetaler gjelder alle regler som ellers i EHF. For betalingsmottaker er krav om organisasjonsnummer og MVA-registrering fjernet i de tilfeller hvor mottaker er en privatperson. I tilfeller hvor mottaker er registrert i Enhetsregisteret skal alle identifikatorer benyttes som for vanlige fakturaer.

[source]
.Betalingsmottaker som er en privatperson
----
<cac:AccountingSupplierParty>
  <cac:Party>
    <cac:PartyName>
      <cbc:Name>Kari Igloskaper</cbc:Name> <!--1-->
    </cac:PartyName>
    <cac:PostalAddress> <!--2-->
      <cbc:StreetName>Torgallmenningen 1337</cbc:StreetName>
      <cbc:CityName>Bergen</cbc:CityName>
      <cbc:PostalZone>5014</cbc:PostalZone>
      <cac:Country>
        <cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
      </cac:Country>
    </cac:PostalAddress>
  </cac:Party>
</cac:AccountingSupplierParty>
----
<1> Navn på betalingsmottaker.
<2> Postadresse til betalingsmottaker.


== Validering

En korrekt dokumentinstans bestående av en utbetalingsanmodning er ventet å ikke generere noen feil eller advarsler utover advarselen "EUGEN-T10-R039".
