= Attachments

Both the invoice and the credit note formats support the use of attachments. The element to hold the attachment information can be repeated multiple times (AdditionalDocumentReference) thus allowing multiple attachments.

Attachments may be used to provide additional information to support the claim represented by the invoice. Additional information can be time sheets, receipts, airfare tickets etc. Attachments are not meant for transferring a pdf-version of the invoice/creditnote.  If, however, the “pdf-version” is supplied as an attachment, the element “DocumentType” must specify “Commercial invoice” for an invoice and “Credit note” for a creditnote. Attachments can also be graphs and images. The attachment could be sent as a binary object or as an external address to the object’s storage location (URI).

It is recommended to send additional information included in the format (message) and not as an external address (URI), since many businesses are restricted from pursuing external links.
If external link is used, the buyer is committed to download the information contained in the link and store it with reference to the invoice/creditnote document.  Such a solution requires according to the Norwegian tax authorities (Skattedirektoratet), an agreement between the parties.  Thus use of external links are not recommended.

Additional recommendations:

Coding::
Base64
Document format::
MIME types:
* Pdf – application / pdf
* TXT – text / txt
* GIF – image / gif
* TIFF – image / tiff
* JPEG, JPG – image / jpeg
* PNG – image / png
Size::
5MB
Description of attachment::
It is advised to supply a good description of each attachment and the element to use is: Invoice/Additional_DocumentReference/DocumentReference/DocumentType. +
Should only be used for description of the document content.

== Copy of the Invoice/Creditnote as an Attachment

There is one special case where it is absolutely required to send the invoice/creditnote as an attachment (cf: FOR 2004-12-01 nr 1558: Forskrift om bokføring). Companies without the ability to send EHF formats will create an invoice or creditnote as usual, e.g. as a document meant to be printed and mailed. Those companies can use an «invoice portal» to register necessary information about the invoice or creditnote and then add a pdf-version or an image of the invoice/creditnote as an attachment. In that case the element DocumentType must specify “Commercial invoice” for an invoice and “Credit note” for a creditnote.
