= Roles and Actor

The following roles may be specified in the format. The same actor may play more than one role depending on the handling routine.

Seller (AccountingSupplierParty)::
Seller is mandatory information in EHF.

Buyer (AccountingCustomerParty)::
Buyer is mandatory information in EHF.

Payment receiver (PayeeParty)::
Payment receiver is optional information in EHF. If this information is not supplied, the seller is the payment receiver.

[source,xml]
.Example: Supplying seller information on the header level in an EHF invoice message.
----
<cac:AccountingSupplierParty>
<cac:Party>
    <cbc:EndpointID schemeID="NO:ORGNR">123456789</cbc:EndpointID>
    <cac:PartyIdentification>
      <cbc:ID schemeID="ZZZ">123456</cbc:ID>
    </cac:PartyIdentification>
    <cac:PartyName>
      <cbc:Name>Salgsbedriften ASA</cbc:Name>
    </cac:PartyName>
    <cac:PostalAddress>
      <cbc:StreetName>Storgata 34</cbc:StreetName>
      <cbc:AdditionalStreetName>Suite 123</cbc:AdditionalStreetName>
      <cbc:CityName>Storevik</cbc:CityName>
      <cbc:PostalZone>1234</cbc:PostalZone>
      <cbc:CountrySubentity>Region A</cbc:CountrySubentity>
      <cac:Country>
        <cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
      </cac:Country>
    </cac:PostalAddress>
    <cac:PartyTaxScheme>
      <cbc:CompanyID schemeID="NO:VAT">123456789MVA</cbc:CompanyID>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:PartyTaxScheme>
    <cac:PartyLegalEntity>
      <cbc:RegistrationName>Salgsbedriften ASA</cbc:RegistrationName>
      <cbc:CompanyID schemeID="NO:ORGNR" schemeName="Foretaksregisteret">123456789</cbc:CompanyID>
      <cac:RegistrationAddress>
        <cbc:CityName>Storevik</cbc:CityName>
        <cac:Country>
          <cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
        </cac:Country>
      </cac:RegistrationAddress>
    </cac:PartyLegalEntity>
    <cac:Contact>
      <cbc:ID>Vår ref</cbc:ID>
      <cbc:Name>Ola Nordmann</cbc:Name>
      <cbc:Telephone>46211230</cbc:Telephone>
      <cbc:Telefax>46211231</cbc:Telefax>
      <cbc:ElectronicMail>ola@salgsbedriften.no</cbc:ElectronicMail>
    </cac:Contact>
  </cac:Party>
</cac:AccountingSupplierParty>
----
 
[source,xml]
.Example: Supplying buyer information on the header level in an EHF invoice message.
----
<cac:AccountingCustomerParty>
  <cac:Party>
    <cbc:EndpointID schemeID="NO:ORGNR">987654321</cbc:EndpointID>
    <cac:PartyIdentification>
      <cbc:ID schemeID="GLN">5790000436033</cbc:ID>
    </cac:PartyIdentification>
    <cac:PartyName>
      <cbc:Name>AS Innkjøper</cbc:Name>
    </cac:PartyName>
    <cac:PostalAddress>
      <cbc:StreetName>Hovedgata 23</cbc:StreetName>
      <cbc:AdditionalStreetName>Bakdøra</cbc:AdditionalStreetName>
      <cbc:CityName>Lillevik</cbc:CityName>
      <cbc:PostalZone>8523</cbc:PostalZone>
      <cbc:CountrySubentity>Region B</cbc:CountrySubentity>
      <cac:Country>
        <cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
      </cac:Country>
    </cac:PostalAddress>
    <cac:PartyTaxScheme>
      <cbc:CompanyID schemeID="NO:VAT">987654321MVA</cbc:CompanyID>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:PartyTaxScheme>
    <cac:PartyLegalEntity>
      <cbc:RegistrationName>AS Innkjøper</cbc:RegistrationName>
      <cbc:CompanyID schemeID="NO:ORGNR">987654321</cbc:CompanyID>
    </cac:PartyLegalEntity>
    <cac:Contact>
      <cbc:ID>3150bdn</cbc:ID>
      <cbc:Name>Kari Navnesen</cbc:Name>
      <cbc:Telephone>5121230</cbc:Telephone>
      <cbc:Telefax>5121231</cbc:Telefax>
      <cbc:ElectronicMail>kari.navnesen@innkjoper.no</cbc:ElectronicMail>
    </cac:Contact>
  </cac:Party>
</cac:AccountingCustomerParty>
----

== Customer Number

The customer number is stated in <cac:PartyIdentification>. Specification of the type of party identification used, is stated in the attribute schemeID. The values must be from the https://joinup.ec.europa.eu/svn/peppol/TransportInfrastructure/PEPPOL%20Policy%20for%20use%20of%20identifiers%20v3%200_2014-02-03.doc[PEPPOL Policy of Identifiers].

The most commonly used identifiers in the Norwegian market is:

[cols="2,7", options="header"]
|===
| SchemeID
| Description

| ZZZ
| Issuer unknown, used for internal customer numbers

| GLN
| Global Location Number issued by GS1

| NO:ORGNR
| Registration in The Brønnøysund Register Centre
|===
