= Rounding

. Rounding shall, as a general rule, be performed on the final result of a calculation only and not on any intermediate calculation, for the result to be mathematically correct.
. Rounding shall result in a decimal figure with 2 decimal places. The third decimal digit being greater than 4 increases the second decimal digit with 1, whilst the third decimal digit being less than 5 leaves the second decimal digit as it is.
. The EHF format assumes that all amounts on the header level have a maximum of 2 decimal places. Calculated amounts with more than 2 decimal places, like most VAT calculations, must be rounded. Results from calculations involving already rounded amounts are not subject to rounding , like payable amounts and total amounts included VAT.

== Elements That Must be Rounded

. One line’s total amount, LineExtensionAmount, must be rounded because it may be subject to posting in an accounting system.  Note that the elements contained in the LineExtensionAmount (Price * Quantity,  Allowances and Charges) must be rounded separately when calculating the LineExtensionAmount.
.* All rounded LineExtensionAmount shall be summed as the total line amount on the header level; MonetaryTotal/Line Extension Amount.
.* The rounded LineExtensionAmount shall be subject to VAT calculation on the header level; Tax Subtotal/ TaxableAmount.
. The sum of the header level allowances must be rounded before it is specified to the element MonetaryTotal/AllowanceTotalAmount.
. The sum of the header level charges must be rounded before it is specified to the element MonetaryTotal/ChargeTotalAmount.
. The element TaxSubTotal/TaxableAmount which holds the value subject to VAT calculation.
. The element TaxSubTotal/TaxAmount which holds the VAT value calculated on the d) value.

== Rounding of the Payable Amount

It is possible to round the payable amount to the nearest integer. The element MonetaryTotal/PayableRoundingAmount is used for this and is specified on the header level.

This value must be added to the value in MonetaryTotal/TaxInclusiveAmount.

Example:  amount  999.81 rounded to  1000.  PayableRounding Amount = 0.19.

== Examples of Rounding

* Invoice with 3 lines:
** Line 1:  24 units of item A.  Kr. 51.304 per unit, 10% discount rate. 25% VAT.
** Line 2:  15 units of item B.  Kr. 44.7823 per unit, 15% discount rate. 25 % VAT.
** Line 3:  21 units of item C.  Kr. 134.95 per unit, 24.45 % discount rate. 15% VAT.
* Discount rate on total: 2.35 %
* Shipping cost:  100.345
* Prepaid amount:  100
* Payable rounding amount: -0.36 (note the negative value)

=== Contents of Amount Elements

[cols="1,*,1,6*", options="header"]
|===
| Line
| Price
| Units
| Discount rate
| Price*units rounded
| Discount rounded
| Line total
| VAT %

| 1
| 51,304
| 24
| 10 %
| 1231,3
| 123,13
>| 1108,17
| 25 %

| 2
| 44,7823
| 15
| 15 %
| 671,73
| 100,76
>| 570,97
| 25 %

| 3
| 134,95
| 21
| 24,45 %
| 2833,95
| 692,9
>| 2141,05
| 15 %

| Total
|
|
|
|
|
>s| 3820,19
|

|===

[cols="5,1,2", options="header"]
|===

| AllowanceCharge (Invoice)
|
| Values unrounded

| Discount on total (25% mva)
| 2,35 %
| 89,774465

| Shipping cost (25% mva)
|
| 100,345
|===

[cols="2,>2,>2,>2,>2", options="header"]
|===

| VAT catg.
| VAT basis
| VAT rate
| VAT calculated
| VAT per category

| S	| 1689,72 | 25 % | 422,43 | 422,43
| H	| 2141,05 | 15 % | 321,1575 | 321,16
| Total VAT s| 3830,77 | | 743,5875 s| 743,59
|===

[cols="5,>2"]
|===
s| Sum all lines >| 3820,19
s| Invoice total exclusive VAT >| 3830,77
s| Invoice total inclusive VAT and rounding >| 4574,00
s| Allowances (discount on total) >| 89,77
s| Charges (shipping cost) >| 100,35
s| Prepaid amount >| 100,00
s| Rounding amount >| -0,36
s| Payable amount >| 4474,00
|===

=== XML for Allowance and Charges on the Header Level

[source,xml]
----
<cac:AllowanceCharge>
	<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReason>2.35% Totalrabatt</cbc:AllowanceChargeReason>
	<cbc:Amount currencyID="NOK">89.7744</cbc:Amount>
	<cac:TaxCategory>
		<cbc:ID schemeID="UNCL5305">S</cbc:ID>
		<cbc:Percent>25.00</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:TaxCategory>
</cac:AllowanceCharge>
<cac:AllowanceCharge>
	<cbc:ChargeIndicator>true</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReason>Frakt</cbc:AllowanceChargeReason>
	<cbc:Amount currencyID="NOK">100.345</cbc:Amount>
	<cac:TaxCategory>
		<cbc:ID schemeID="UNCL5305">S</cbc:ID>
		<cbc:Percent>25.00</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:TaxCategory>
</cac:AllowanceCharge>
----

=== XML for VAT on the Header Level

[source,xml]
----
<cac:TaxTotal>
	<cbc:TaxAmount currencyID="NOK">743,59</cbc:TaxAmount>
	<cac:TaxSubtotal>
		<cbc:TaxableAmount currencyID="NOK">1689.72</cbc:TaxableAmount>
		<cbc:TaxAmount currencyID="NOK">422.43</cbc:TaxAmount>
		<cac:TaxCategory>
			<cbc:ID schemeID="UNCL5305">S</cbc:ID>
			<cbc:Percent>25.00</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:TaxCategory>
	</cac:TaxSubtotal>
	<cac:TaxSubtotal>
		<cbc:TaxableAmount currencyID="NOK">2141.05</cbc:TaxableAmount>
		<cbc:TaxAmount currencyID="NOK">321.16</cbc:TaxAmount>
		<cac:TaxCategory>
			<cbc:ID schemeID="UNCL5305">H</cbc:ID>
			<cbc:Percent>15.00</cbc:Percent>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:TaxCategory>
	</cac:TaxSubtotal>
</cac:TaxTotal>
----

=== XML for Totals on the Header Level

[source,xml]
----
<cac:LegalMonetaryTotal>
	<cbc:LineExtensionAmount currencyID="NOK">3820.19</cbc:LineExtensionAmount>
	<cbc:TaxExclusiveAmount currencyID="NOK">3830.77</cbc:TaxExclusiveAmount>
	<cbc:TaxInclusiveAmount currencyID="NOK">4574.00</cbc:TaxInclusiveAmount>
	<cbc:AllowanceTotalAmount currencyID="NOK">89.77</cbc:AllowanceTotalAmount>
	<cbc:ChargeTotalAmount currencyID="NOK">100.35</cbc:ChargeTotalAmount>
	<cbc:PrepaidAmount currencyID="NOK">100.00</cbc:PrepaidAmount>
	<cbc:PayableRoundingAmount currencyID="NOK">-0.36</cbc:PayableRoundingAmount>
	<cbc:PayableAmount currencyID="NOK">4474.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
----

=== XML for Invoice Lines

[source,xml]
.Line 1
----
<cbc:ID>1</cbc:ID>
<cbc:InvoicedQuantity unitCode="NAR">24.00</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="NOK">1108.17</cbc:LineExtensionAmount>
<cbc:AccountingCost>123</cbc:AccountingCost>
<cac:OrderLineReference>
	<cbc:LineID>1</cbc:LineID>
</cac:OrderLineReference>
<cac:AllowanceCharge>
	<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReason>10% Rabatt</cbc:AllowanceChargeReason>
	<cbc:Amount currencyID="NOK">123.1296</cbc:Amount>
</cac:AllowanceCharge>
<cac:Item>
	<cbc:Name>Vare A</cbc:Name>
	<cac:SellersItemIdentification>
		<cbc:ID>AAA</cbc:ID>
	</cac:SellersItemIdentification>
	<cac:ClassifiedTaxCategory>
		<cbc:ID schemeID=" UNCL5305">S</cbc:ID>
		<cbc:Percent>25.00</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:ClassifiedTaxCategory>
</cac:Item>
<cac:Price>
	<cbc:PriceAmount currencyID="NOK">51.304</cbc:PriceAmount>
</cac:Price>
----

[source,xml]
.Line 2
----
<cbc:ID>2</cbc:ID>
<cbc:InvoicedQuantity unitCode="NAR">15.00</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="NOK">570.97</cbc:LineExtensionAmount>
<cbc:AccountingCost>123</cbc:AccountingCost>
<cac:OrderLineReference>
  <cbc:LineID>2</cbc:LineID>
</cac:OrderLineReference>
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReason>15% Rabatt</cbc:AllowanceChargeReason>
  <cbc:Amount currencyID="NOK">100.760175</cbc:Amount>
</cac:AllowanceCharge>
<cac:Item>
 	<cbc:Name>Vare B</cbc:Name>
  <cac:SellersItemIdentification>
 		<cbc:ID>BBB</cbc:ID>
 	</cac:SellersItemIdentification>
  <cac:ClassifiedTaxCategory>
   	<cbc:ID schemeID=" UNCL5305">S</cbc:ID>
   	<cbc:Percent>25.00</cbc:Percent>
    <cac:TaxScheme>
   		<cbc:ID>VAT</cbc:ID>
   	</cac:TaxScheme>
  </cac:ClassifiedTaxCategory>
</cac:Item>
<cac:Price>
	<cbc:PriceAmount currencyID="NOK">44.7823</cbc:PriceAmount>
</cac:Price>
----

[source,xml]
.Line 3
----
<cbc:ID>3</cbc:ID>
<cbc:InvoicedQuantity unitCode="NAR">21.00</cbc:InvoicedQuantity>
<cbc:LineExtensionAmount currencyID="NOK">2141.05</cbc:LineExtensionAmount>
<cbc:AccountingCost>123</cbc:AccountingCost>
<cac:OrderLineReference>
	<cbc:LineID>2</cbc:LineID>
</cac:OrderLineReference>
<cac:AllowanceCharge>
	<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReason>24.45% Rabatt</cbc:AllowanceChargeReason>
	<cbc:Amount currencyID="NOK">692.9007</cbc:Amount>
</cac:AllowanceCharge>
<cac:Item>
	<cbc:Name>Vare C</cbc:Name>
	<cac:SellersItemIdentification>
		<cbc:ID>CCC</cbc:ID>
	</cac:SellersItemIdentification>
	<cac:ClassifiedTaxCategory>
		<cbc:ID schemeID=" UNCL5305">H</cbc:ID>
		<cbc:Percent>15.00</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:ClassifiedTaxCategory>
</cac:Item>
<cac:Price>
	<cbc:PriceAmount currencyID="NOK">134.95</cbc:PriceAmount>
</cac:Price>
----
