= Use of Supplier and Customer Contacts

The customer contact, known as Your ref or “ Deres ref” in Norwegian, is **mandatory**. The element is used for the reference of who ordered the products/services. Example being the name of the person ordering, employee number or a code identifying this person or department/group. Your ref is often used for internal routing at recipient, and hence it is important to fill this element with the correct values according to the need of the recipient. If this information is not relevant for the invoice, the value “NA” (Not Applicable) should be used, this should be agreed with invoice recipient. Information and is specified in the element `AccountingCustomerParty/Party/Contact/ID`.

IMPORTANT: "Your ref" must be set to "NA" only in situations where such a reference is not provided by customer. When reference is provided by customer must correct element contain the provided reference.

The supplier contact, known as “Vår ref” in Norwegian, is **recommended** in EHF. Name/reference/identificator of the person that can answer any questions regarding the invoice/credit note. Information and is specified in the element `AccountingSupplierParty/Party/Contact/ID`.
