= Valideringsprinsipper

Nivåer i valideringsprosessen:

.	Validering av syntaks mot UBL XML Schema, for eksempel:
  * Tagnavn og eventuelle attributter må være korrekt skrevet og i riktig rekkefølge i henhold til UBL.
  * Alle obligatoriske tagnavn ihht UBL må være inkludert.
  * Innholdet i et element må ha lovlig verdi i henhold til type definisjon.
.	Validering mot CEN BII for å sikre at meldingen er i henhold til internasjonale krav, for eksempel:
  * Lovlige koder for valuta, land, avgifter etc.
  * Logiske sammenhenger mellom informasjonselementer som at startdato må komme før sluttdato, subtotaler må summeres til korrekt totalsum, test på at faktorer som skal multipliseres får korrekt produkt etc.
.	Validering mot PEPPOL (EU) regelverk
. Validering mot EHF Common som inneholder regler felles for alle dokumenttyper som inngår i EHF.
.	Validering mot EHF regler og norsk lovverk, for eksempel:
  * Organisasjonsnummer må fylles ut for selger.
  * Deres referanse må være utfylt.
  * Adresse, postnr og sted må være utfylt for kjøper.
