= Financial Advance vs. Account Invoicing

Financial advance is not previously invoiced, ref. «Skattedirektoratets uttalelse av 23.05.07 link:http://www.skatteetaten.no/no/Radgiver/Rettskilder/Uttalelser/Prinsipputtalelser/Finansielle-forskudd-eller-forskuddsfakturering/[Finansielle forskudd eller forskuddsfakturering] og link:http://www.regnskapsstiftelsen.no/bokforing/uttalelser-om-god-bokforingsskikk-gbs/gbs-13-forskuddsfakturering/[GBS 13 Forskuddsfakturering].», in English: «Directorate of taxes, statement 23.05.2007: Financial advance or advance billing and GBS13 Advance billing». This means that when the goods or services are delivered an invoice must be issued according to the rules in the Accounting regulations § 5-1 and § 5-2 even if the economic considerations already are levied through financial advance. The invoice settles the financial advance. If the economic considerations exceed the financial advance, the buyer must pay the excessive amount. If the economic considerations are lower than the financial advance, a negative invoice occurs, and the seller must repay the negative invoice amount.

In cases of financial advance or on account invoicing a credit note must be issued following the rules of the "Accounting regulations § 5-2-8" and link:http://www.regnskapsstiftelsen.no/bokforing/uttalelser-om-god-bokforingsskikk-gbs/gbs-1-utstedelse-av-kreditnota/["GBS 1 Issuing a credit note"] to settle the previous invoice (if the specified considerations were too high).
