= Use of Party Tax Scheme for Accounting Supplier Party

PartyTaxScheme under AccountingSupplierParty is an optional  element, but according to EU COUNCIL DIRECTIVE 2001/115/ the PartyTaxScheme must be specified if the invoice or the credit note have a VAT total. That means that the element almost always has to be specified. The specification should be the supplier party’s organization number followed by the letters MVA, like this:

[source,xml]
----
<cac:PartyTaxScheme>
	<cbc:CompanyID schemeID="NO:VAT">123456789MVA</cbc:CompanyID>
	<cac:TaxScheme>
		<cbc:ID>VAT</cbc:ID>
	</cac:TaxScheme>
</cac:PartyTaxScheme>
----

== Suppliers not registered for VAT

Suppliers that is not registered for VAT, cannot send invoices with VAT amounts > 0. VAT Categories must be set to "Z", and all VAT amounts must be 0,-. The element 'cac:PartyTaxScheme' must be omitted.

.Example supplier information:
[source, xml]
----
<cac:AccountingSupplierParty>
	<cac:Party>
		<cbc:EndpointID schemeID="NO:ORGNR">999888777</cbc:EndpointID>
		<cac:PartyIdentification>
			<cbc:ID schemeID="GLN">1234567898765</cbc:ID>
		</cac:PartyIdentification>
		<cac:PartyName>
			<cbc:Name>Bedriften A/S</cbc:Name>
		</cac:PartyName>
		<cac:PostalAddress>
			<cbc:StreetName>Brugt. 10</cbc:StreetName>
			<cbc:CityName>Sarpsborg</cbc:CityName>
			<cbc:PostalZone>1710</cbc:PostalZone>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Supplier without VAT</cbc:RegistrationName>
			<cbc:CompanyID schemeID="NO:ORGNR">999888222</cbc:CompanyID>
			<cac:RegistrationAddress>
				<cbc:CityName>Sarpsborg</cbc:CityName>
				<cac:Country>
					<cbc:IdentificationCode listID="ISO3166-1:Alpha2">NO</cbc:IdentificationCode>
				</cac:Country>
			</cac:RegistrationAddress>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:ID>abc1234</cbc:ID>
		</cac:Contact>
	</cac:Party>
</cac:AccountingSupplierParty>
----

.Example VAT and total amounts:
[source, xml]
----
<cac:TaxTotal>
		<cbc:TaxAmount currencyID="NOK">0.00</cbc:TaxAmount>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="NOK">100.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="NOK">0.00</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID schemeID="UNCL5305">Z</cbc:ID>
				<cbc:Percent>0</cbc:Percent>
				<cac:TaxScheme>
					<cbc:ID>VAT</cbc:ID>
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
	</cac:TaxTotal>

	<cac:LegalMonetaryTotal>
		<cbc:LineExtensionAmount currencyID="NOK">100.00</cbc:LineExtensionAmount>
		<cbc:TaxExclusiveAmount currencyID="NOK">100.00</cbc:TaxExclusiveAmount>
		<cbc:TaxInclusiveAmount currencyID="NOK">100.00</cbc:TaxInclusiveAmount>
		<cbc:PayableAmount currencyID="NOK">100.00</cbc:PayableAmount>
	</cac:LegalMonetaryTotal>
----

.Example VAT on invoice line:
[source, xml]
----
<cac:ClassifiedTaxCategory>
	<cbc:ID schemeID="UNCL5305">Z</cbc:ID>
		<cbc:Percent>0</cbc:Percent>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
</cac:ClassifiedTaxCategory>
----
