= Finansielt forskudd vs. A konto faktura

Finansielle forskudd skal ikke være fakturert tidligere, jf. Skattdirektoratets uttalelse av 23.05.07 link:http://www.skatteetaten.no/no/Uttalelser/Finansielle-forskudd-eller-forskuddsfakturering/[Finansielle forskudd eller forskuddsfakturering] og link:http://www.regnskapsstiftelsen.no/arch/_img/9505478.pdf[GBS 13 Forskuddsfakturering]. Dette betyr at når varen eller tjenesten er levert skal det utstedes et salgsdokument (faktura) etter reglene i link:http://www.lovdata.no/for/sf/fd/td-20041201-1558-005.html#5-1[bokføringsforskriften § 5-1 og § 5-2] selv om vederlaget allerede er innkrevd gjennom et finansielt forskudd. Salgsdokumentet avregnes mot det finansielle forskuddet. Dersom vederlaget overskrider det finansielle forskuddet, må kjøper innbetale restbeløpet. Dersom vederlaget er lavere enn det finansielle forskuddet oppstår det en ”negativ faktura”, altså hvor selger må tilbakebetale det overskytende beløpet.

I tilfeller med forskudds- eller akonto-fakturering må det utstedes en kreditnota etter reglene i link:http://www.lovdata.no/for/sf/fd/td-20041201-1558-005.html#5-2-8[bokføringsforskriften § 5-2-8] og link:http://www.regnskapsstiftelsen.no/arch/_img/9505436.pdf[GBS 1 Utstedelse av kreditnota] for å korrigere det tidligere salgsdokumentet (som viste seg å angi et for høyt vederlag).  Dette gjelder ikke hvis den negative fakturaen inneholder salg av nye varer og tjenester.
