= Logistics Information

EHF Catalogue includes elements to support the need for logistics information which is a requirement in many industries in the Norwegian market. These elements are not mandatory, but trading partners can agree upon the use in the commercial agreements.

The Logistics elements can be used to specify different pack levels for the same article. This must be done as follows:

* Each pack level is regarded as a unique product and must be sent as a separate Catalogue line and identified with a unique ID such as GTIN.
* Information about pack level is done in the element PackLevelCode on line level. The Pack level codes are based on the Edifact/Eancom-standard and the following codes are available (codes in brackets are used in some business sectors in Norway):
** DU = Dispatch Unit (T-Pak or Pall)
** HN = Handling Unit (level between TU and DU). Not commonly used.
** TU = Traded Unit (D-Pak or L-Pak)
** CU = Consumer Unit (F-Pak)
* It must be stated if the pack level is orderable.
* The relation between pack levels must be specified, e.g. that a Dispatch unit contains Traded units.

Below is an example of Logistics information in an EHF Catalogue message.

.The example shows a Dispatch unit (DU) containing a Traded unit containing a Consumer unit.
====

[source]
.Catalogue line for Dispatch unit, highest pack level.
----
<cac:CatalogueLine>
  <cbc:ID>1</cbc:ID>
  <cbc:ActionCode listID="ACTIONCODE:BII2">Add</cbc:ActionCode>
  <cbc:OrderableIndicator>false</cbc:OrderableIndicator>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">DU</cbc:PackLevelCode>
  <cac:ComponentRelatedItem>
    <cbc:ID>2</cbc:ID>
    <cbc:Quantity unitCode="EA" unitCodeListID="UNECERec20">12</cbc:Quantity>
  </cac:ComponentRelatedItem>
  <cac:Item>
    <cbc:Description>Soft drink, pallet</cbc:Description>
    <cbc:PackQuantity unitCode="EA" unitCodeListID="UNECERec20">1</cbc:PackQuantity>
    <cbc:Name languageID="en">Soft drink</cbc:Name>
    <cac:SellersItemIdentification>
      <cbc:ID>111111</cbc:ID>
    </cac:SellersItemIdentification>
  </cac:Item>
</cac:CatalogueLine>
----

[source]
.Catalogue line for Traded unit.
----
<cac:CatalogueLine>
  <cbc:ID>2</cbc:ID>
  <cbc:ActionCode listID="ACTIONCODE:BII2">Add</cbc:ActionCode>
  <cbc:OrderableIndicator>true</cbc:OrderableIndicator>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">TU</cbc:PackLevelCode>
  <cac:ComponentRelatedItem>
    <cbc:ID>3</cbc:ID>
    <cbc:Quantity unitCode="EA" unitCodeListID="UNECERec20">6</cbc:Quantity>
  </cac:ComponentRelatedItem>
  <cac:Item>
    <cbc:Description>Soft drink, trading unit</cbc:Description>
    <cbc:PackQuantity unitCode="EA" unitCodeListID="UNECERec20">1</cbc:PackQuantity>
      <cbc:Name languageID="en">Soft drink</cbc:Name>
    <cac:SellersItemIdentification>
      <cbc:ID>222222</cbc:ID>
    </cac:SellersItemIdentification>
  </cac:Item>
</cac:CatalogueLine>
----

[source]
.Catalogue line for Consumer unit, lowest pack level.
----
<cac:CatalogueLine>
  <cbc:ID>3</cbc:ID>
  <cbc:ActionCode listID="ACTIONCODE:BII2">Add</cbc:ActionCode>
  <cbc:OrderableIndicator>false</cbc:OrderableIndicator>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">CU</cbc:PackLevelCode>
  <cac:Item>
    <cbc:Description>Soft drink 4-pack</cbc:Description>
    <cbc:PackQuantity unitCode="EA" unitCodeListID="UNECERec20">1</cbc:PackQuantity>
      <cbc:Name languageID="en">Soft drink</cbc:Name>
    <cac:SellersItemIdentification>
      <cbc:ID>333333</cbc:ID>
    </cac:SellersItemIdentification>
  </cac:Item>
</cac:CatalogueLine>
----
====
