= Quantities and Units

Various quantities and units can be stated in the EHF Catalogue. These are both related to the ordering process and the logistics process.

The table below lists quantities and units in the format. To all quantities there must be a legal Unit according to the Code list.

Orderable unit (OrderableUnit)::
The unit in which the item described in this catalogue line can be ordered. Mandatory if the item is orderable.

Item net quantity (ContentUnitQuantity)::
The net quantity of the item that is contained in each consumable unit (excluding packaging material), e.g. ml in bottles of Shampoo.

Order  quantity increment (OrderQuantityIncrementNumeric)::
Possible limitation to the number of articles that can be ordered. If the Quantity increment is 6 the article must be ordered in a quantity of 6, 12, 18 etc.

Minimum order quantity (MinimumOrderQuantity)::
The smallest number of items that can be ordered (most often 1).

Maximum order quantity (MaximumOrderQuantity)::
The largest number of items that can be ordered (most often unlimited).

Packed quantity (Item/PackQuantity)::
Number of items on next lower level, e.g. number of Consumer units in a Trading unit.

Consumable unit quantity (Item/PackSizeNumeric)::
Number of Consumer items in the orderable unit. E.g. number of bottles on a Pallet.

.Example 1
====

[cols="5h,2,2,2,2", options="header"]
|===
| Description | Element (from CatalogueLine level)| 1 bottle | Case of 6 bottles | Pallet of 18 cases
| Line identifier | ID | 4 | 5 | 6
| Sellers item identifier |SellersItemIdentification/ID | 1111 | 111 | 11
| Item name | Item/Name |	Shampoo 250 ml | 6x250 ml Shampoo | Shampoo
| Orderable unit| OrderableUnit | EA | CS | PF
| Packaging level | PackLevelCode | CU | TU | DU
| Packed quantity | Item/PackQuantity | | 6 | 18
| Packed quantity unit | Item/PackQuantity/@unitCode | | EA | CS
| Consumable unit quantity | Item/PackSizeNumeric | 1 | 6 | 108
| Item net quantity | ContentUnitQuantity | 250 | 1500 | 27000
| Item net quantity unit |ContentUnitQuantity/@unitCode | MLT | MLT | MLT
| Minimum order quantity | MinimumOrderQuantity | 1 | 1 | 1
| Minimum order quantity unit | MinimumOrderQuantity/@unitCode | EA | EA | EA
| Component related item identifier | ComponentRelatedItem/ID | |1111 | 111
| Item quantity for component related item | ComponentRelatedItem/Quantity | | 6 | 18
|===

[source]
.Example of catalogue line with line identifier = 4 in the above table
----
<cac:CatalogueLine>
  <cbc:ID>4</cbc:ID>
  <cbc:OrderableUnit>EA</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="MLT" unitCodeListID="UNECERec20">250</cbc:ContentUnitQuantity>
  <cbc:OrderQuantityIncrementNumeric>1</cbc:OrderQuantityIncrementNumeric>
  <cbc:MinimumOrderQuantity unitCode="EA" unitCodeListID="UNECERec20">1</cbc:MinimumOrderQuantity>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">CU</cbc:PackLevelCode>
  ...
  <cac:Item>
    <cbc:Name languageID="en">Shampoo 250 ml</cbc:Name>
    <cbc:PackSizeNumeric>1</cbc:PackSizeNumeric>
    <cac:SellersItemIdentification>
      <cbc:ID>1111</cbc:ID>
    </cac:SellersItemIdentification>
  ...
  </cac:Item>
  ...
</cac:CatalogueLine>
----
====

.Example 2
====

[cols="5h,2,2,2,2", options="header"]
|===
| Description | Element (from CatalogueLine level)| Pack of 500 sheets paper | Case of 5 packs paper | Pallet with 18 cases paper
| Line identifier | ID | 7 | 8 | 9
| Sellers item identifier  |SellersItemIdentification/ID | A | AA | AAA
| Item name | Item/Name | 500 copy paper | 5*500 Copy paper | Pallet of paper
| Orderable unit| OrderableUnit | EA | CS | PX
| Packaging level | PackLevelCode | CU | TU | DU
| Packed quantity | Item/PackQuantity | | 5 | 18
| Packed quantity unit | Item/PackQuantity/@unitCode | | EA | CS
| Consumable unit quantity  | Item/PackSizeNumeric | 1 | 5 | 90
| Item net quantity |ContentUnitQuantity| 500 | 2500 | 45000
| Item net quantity unit |ContentUnitQuantity/@unitCode | EA | EA | EA
| Minimum order quantity | MinimumOrderQuantity | 1 | 1 | 1
| Minimum order quantity unit | MinimumOrderQuantity/@unitCode | EA | EA | EA
| Component related item identifier | ComponentRelatedItem/ID  | | A | AA
| Item quantity for component related item | ComponentRelatedItem/Quantity  | | 5 | 18
|===

[source]
.Example of catalogue line with line identifier = 8 in the above table
----
<cac:CatalogueLine>
  cbc:ID>8</cbc:ID>
  <cbc:OrderableUnit>CS</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="EA" unitCodeListID="UNECERec20">2500</cbc:ContentUnitQuantity>
  <cbc:OrderQuantityIncrementNumeric>1</cbc:OrderQuantityIncrementNumeric>
  <cbc:MinimumOrderQuantity unitCode="CS" unitCodeListID="UNECERec20">1</cbc:MinimumOrderQuantity>
  <cbc:PackLevelCode listID="GS17009:PEPPOL">TU</cbc:PackLevelCode>
  <cac:ComponentRelatedItem>
    <cbc:ID>A</cbc:ID>
    <cbc:Quantity unitCode="EA" unitCodeListID="UNECERec20">5</cbc:Quantity>
  </cac:ComponentRelatedItem>
  ...
  <cac:Item>
    <cbc:Description languageID="en">5*500 Copy paper</cbc:Description>
    <cbc:PackQuantity unitCode="CS" unitCodeListID="UNECERec20">5</cbc:PackQuantity>
    <cbc:PackSizeNumeric>5</cbc:PackSizeNumeric>
    <cac:SellersItemIdentification>
      <cbc:ID>AA</cbc:ID>
    </cac:SellersItemIdentification>
    ...
  </cac:Item>
  ...
</cac:CatalogueLine>
----
====


= Catch Weight

To inform that an item is catch weight (ex. Orderable quantity is pcs, but invoiced quantity is kilo, and  where one pcs can be of variable weight), set unit code for content unit to 31 (catch weight) according to UN Recommondations 20.

[source]
.Example
----
<cac:CatalogueLine>
  <cbc:ID>8</cbc:ID>
  <cbc:OrderableUnit>EA</cbc:OrderableUnit>
  <cbc:ContentUnitQuantity unitCode="31" unitCodeListID="UNECERec20">10
</cbc:ContentUnitQuantity>
----
